import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Loading from "./loading";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="border-amber-900">
        <Suspense fallback={<Loading />}>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </Suspense>
      </body>
    </html>
  );
}
